#!/bin/bash

# Set the boot screen data and enable custom boot screen

opt_set BOOTSCREEN_TIMEOUT "1500"

cp $CFGDIR/bootscreens/data/anet/_Bootscreen.h Marlin/
opt_enable SHOW_CUSTOM_BOOTSCREEN

echo "- Added and Enabled Anet Boot Screen" >> README.md