#!/bin/bash

# Set the boot screen data and enable custom boot screen

opt_set BOOTSCREEN_TIMEOUT "1500"

cp $CFGDIR/bootscreens/data/v1/_Bootscreen.h Marlin/
opt_enable SHOW_CUSTOM_BOOTSCREEN

echo "- Added and Enabled V1 Boot Screen" >> README.md