#!/bin/bash

set -e

restore_configs

export MB_VERSION=${MB_VERSION}DL

opt_set CUSTOM_MACHINE_NAME "\"Ender-3 V2 ${MB_VERSION}\""

$CFGDIR/boards/skr_e3_v3

echo "- Configured for Ender 3 V2 SKR" >> README.md

export PLATFORMIO_ENV=STM32G0B1RE_btt