#!/bin/bash

set -e

restore_configs

export MB_VERSION=${MB_VERSION}DL

opt_set CUSTOM_MACHINE_NAME "\"Ender-3 V2 ${MB_VERSION}\""

$CFGDIR/boards/creality_v4_2_2

echo "- Configured for Ender 3 V2" >> README.md

export PLATFORMIO_ENV=STM32F103RET6_creality