#!/bin/bash

set -e

restore_configs

export MB_VERSION=${MB_VERSION}DL

opt_set CUSTOM_MACHINE_NAME "\"V1 LR2 SKR1.3 TMC2130 ${MB_VERSION}\""

$CFGDIR/common/ned-base-config
$CFGDIR/common/cnc-config
$CFGDIR/bootscreens/v1
$CFGDIR/boards/skr_1p3
$CFGDIR/accessories/tmc2130
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/dual-drivers-on-yz
$CFGDIR/accessories/sensorless-homing
$CFGDIR/accessories/use-32-microsteps-z-2mm
$CFGDIR/accessories/z-probe-0-0
$CFGDIR/accessories/auto-bed-leveling
$CFGDIR/accessories/auto-z-leveling-big-bed
$CFGDIR/accessories/scew-correction
$CFGDIR/accessories/babystepping
$CFGDIR/accessories/cnc-menu-items

# Machine specific Overrides/Settings
opt_set DEFAULT_MAX_FEEDRATE "{ 150, 150, 10 }"
opt_set X_BED_SIZE "1554"
opt_set Y_BED_SIZE "3100"

opt_set GRID_MAX_POINTS_X "5"
opt_set GRID_MAX_POINTS_Y "7"

opt_set MANUAL_X_HOME_POS "-25"
opt_set MANUAL_Y_HOME_POS "-25"
opt_set MANUAL_Z_HOME_POS "65"
opt_set HOMING_BACKOFF_POST_MM "{ 0-MANUAL_X_HOME_POS, 0-MANUAL_Y_HOME_POS, 5 }"

opt_set HOMING_FEEDRATE_MM_M "{ (50*60), (50*60), (5*60) }"

opt_set DEFAULT_AXIS_STEPS_PER_UNIT "{ 200, 200, 3200 }"
opt_set AXIS_RELATIVE_MODES '{ false, false, false }'
opt_set DISABLE_INACTIVE_Z "true"

opt_set CHOPPER_TIMING "CHOPPER_DEFAULT_24V"

# TMC2209: 0...255. TMC2130: -64...63
opt_set X_STALL_SENSITIVITY  "6"
opt_set Y_STALL_SENSITIVITY  "2"
opt_set Y2_STALL_SENSITIVITY "8"
opt_set Z_STALL_SENSITIVITY  "-1"

opt_enable HYBRID_THRESHOLD
opt_set X_HYBRID_THRESHOLD "20"
opt_set X2_HYBRID_THRESHOLD "20"
opt_set Y_HYBRID_THRESHOLD "20"
opt_set Y2_HYBRID_THRESHOLD "20"

opt_enable USE_XMAX_PLUG
opt_enable USE_YMAX_PLUG
opt_enable USE_ZMAX_PLUG

opt_enable INVERT_Y2_VS_Y_DIR

opt_set XY_PROBE_FEEDRATE "(100*60)"
opt_set Z_PROBE_FEEDRATE_FAST "(5*60)"
opt_set Z_MIN_PROBE_PIN "P1_24"

opt_enable JOYSTICK
opt_enable JOYSTICK_DEBUG
opt_set JOY_X_PIN "P0_25"
opt_set JOY_Y_PIN "P0_24"
opt_set JOY_Z_PIN "P0_23"
opt_set JOY_EN_PIN "P2_00"

opt_set JOY_X_LIMITS "{ 0, 3226-100, 3226+100, 4095 }"
opt_set JOY_Y_LIMITS "{ 0, 3251-100, 3251+100, 4095 }"
opt_set JOY_Z_LIMITS "{ 0, 3258-100, 3258+100, 4095 }"

export PLATFORMIO_ENV=LPC1768
