#!/bin/bash

# Set up the custom version strings here.

export MB_VERSION=${MB_VERSION:-$(git rev-parse --short HEAD)}
export MARLIN_VERSION="${MARLIN_VERSION:-Custom}"
export CONFIG_NAME="${CONFIG_NAME:-ConfigUnknown}"

# Let's get a number for the version from the build, so we can try some basic maths.
export MARLIN_CONFIG_VERSION=`grep CONFIGURATION_H_VERSION ${MARLINDIR}/Marlin/Configuration.h | cut -d" " -f3`
